name: 'gcloud'

on:
  push:
    branches:
    - ci
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gcloud:
    name: 'Provision GCP'
    runs-on: ubuntu-latest
    environment: production
    env:
      REGION : 'europe-west2'
      PROJECT : 'alconost-sandbox'
      REPO : 'nginx'
      IMAGE : 'nginx'
      TAG : 'v1'
      SERVICE_NAME: alconost-cloudrun

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
    # Setup gcloud CLI
    - name: 'Set up gcloud cli'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
   
    - name: 'Creating CloudRun service'
      env:
        IMAGE_URL: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.TAG }}
        PORT: 80
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} --image=${{ env.IMAGE_URL }} --port=${{ env.PORT }} --region=${{ env.REGION }} --allow-unauthenticated

    - name: 'Creating CloudSQL DB instance'
      env:
        INSTANCE_NAME: alconost-db-instance-${{ github.sha }}
        DB_TYPE: MYSQL_8_0
        DB_TIER: db-f1-micro
        ROOT_PASS: ${{ secrets.GCP_DB_ROOT_PASSWORD }}
      run: |
        gcloud sql instances create ${{ env.INSTANCE_NAME }} --database-version=${{ env.DB_TYPE }} --tier=${{ env.DB_TIER }} --region=${{ env.REGION }} --root-password=${{ env.ROOT_PASS }}
      
    - name: 'Getting CloudRun service URL'
      run: |
        echo ::set-output name=service_url::$(gcloud run services describe ${{ env.SERVICE_NAME }} --platform-managed --region ${{ env.REGION }} --format 'value(status.url)')
        
    - name: 'Performing tests'
      run: |
        echo "Perform some auto-tests"
        echo "Service URL: ${{ steps.vars.outputs.service_url }}"
        sleep 300s
      shell: bash

    - name: 'Deleting CloudRun'
      if: always()
      run: |
        gcloud beta run services delete ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --quiet
