name: 'Terraform'

on:
  push:
    branches:
    - ci
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    name: 'Provision GCP'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    # On push to terraform branch, build or change infrastructure according to Terraform configuration files
    #if: github.ref == 'refs/heads/terraform' && github.event_name == 'push'

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # # Checks that all Terraform configuration files adhere to a canonical format
    # - name: Terraform Format
    #   run: terraform fmt -check

    # Setup gcloud CLI
    id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
   
    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan

    # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". 
    # See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      # If any commit message in your push or the HEAD commit of your PR 
      # contains the strings <construire> -- then terraform Apply step will run
      #if: "contains(github.event.commits[0].message, '[construire]')"
      # terraform plan
      run: |
       terraform apply -auto-approve
    - name: Terraform Destroy
      # If any commit message in your push or the HEAD commit of your PR 
      # contains the strings [detruire] -- then terraform Destry step will run
      if: "contains(github.event.commits[0].message, '[detruire]')"
      # terraform plan -destroy
      run: |
       terraform apply -destroy -auto-approve
