name: 'Terraform'

on:
  push:
    branches:
    - ci
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    name: 'Provision GCP'
    runs-on: ubuntu-latest
    environment: production
    env:
      REGION : 'europe-west2'
      PROJECT : 'alconost-sandbox'
      REPO : 'nginx'
      IMAGE : 'nginx'
      TAG : 'v1'
      SERVICE_NAME: alconost-cloudrun

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Setup gcloud CLI
    - name: 'Set up gcloud cli'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
   
    - name: 'Creating CloudRun service'
      env:
        IMAGE_URL: ${REGION}-docker.pkg.dev/${PROJECT}/${REPO}/${IMAGE}:${TAG}
        PORT: 80
      run: |
        gcloud run deploy ${SERVICE_NAME} --image=${IMAGE_URL} --port=${PORT} --region=${REGION} --allow-unauthenticated

    - name: 'Creating CloudSQL DB instance'
      env:
        INSTANCE_NAME: alconost-db-instance-${GITHUB_SHA}
        DB_TYPE: MYSQL_8_0
        DB_TIER: db-f1-micro
        ROOT_PASS: ${{ secrets.GCP_DB_ROOT_PASSWORD }}
      run: |
        gcloud sql instances create ${INSTANCE_NAME} --database-version=${DB_TYPE} \
        --tier=${DB_TIER} --region=${REGION} --root-password=${ROOT_PASS}
      
    - name: 'Getting CloudRun service URL'
      run: |
        echo ::set-output name=service_url::$(gcloud run services describe ${SERVICE_NAME} --platform-managed --region ${REGION} --format 'value(status.url)')
        
    - name: 'Performing tests'
      run: |
        echo "Perform some auto-tests"
        echo "Service URL: ${{ steps.vars.outputs.service_url }}"
        sleep 300s
      shell: bash

    - name: 'Deleting CloudRun'
      run: |
        gcloud beta run services delete ${SERVICE_NAME} --quiet
