
name: GCR-Cleaner

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:


jobs:
  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    steps:
      # configure based on your registry
      - uses: 'docker/login-action@v2'
        with:
          registry: gcr.io
          username: ${{ secrets.GCR_USERNAME }}
          password: ${{ secrets.GCR_PASSWORD }}

      # customize based on the gcr-cleaner flags
      - uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=gcr.io/alconost-sandbox/testimage
            -grace=1h
 
